# Generated by Django 2.2.4 on 2022-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(related_name='order_product', to='app1.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='categotry',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='product', to='app1.categories'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
