# Generated by Django 2.2.4 on 2022-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_orders_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='model_y',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
