# Generated by Django 2.2.4 on 2022-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20221011_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='state',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
