# Generated by Django 2.2.4 on 2022-10-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_products_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='model_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
